import 'package:app_in_mail/constants/strings/string_keys.dart';
///english translations, each new String must be also added to the other
///translation files and the key must be a constant
final localizedStringsEn = {
  Strings.inbox: 'Inbox',
  Strings.enter: 'NEXT',
  Strings.errorWhileGettingEmailsList: 'Error while getting emails list.',
  Strings.errorWhileTryingToSignIn: 'Error while trying to sign in',
  Strings.email: 'E-mail',
  Strings.password: 'Password',
  Strings.signIn: 'Sign in with login',
  Strings.logout: 'Logout',
  Strings.invalidCredentials: "Invalid user name or password.",
  Strings.noInternet: 'You are not connected to internet.',
  Strings.welcomeTitle1: "Email became",
  Strings.welcomeTitle2: "active!",
  Strings.welcomeMsg: "If earlier the emails contained only text and graphics, now the emails have actions! Email content became active - interact with it like with App!",
  Strings.welcomeBtnOK: "OKAY,I SEE",
  Strings.registerMsg: 'Do not have an account?',
  Strings.registerBtn: "Sign Up",
  Strings.forgotPasswordBtn: "Forgot password?",
  Strings.moveTo: 'Move to',
  Strings.markAsUnread: 'Mark as unread',
  Strings.delete: 'Delete',
  Strings.exchange: 'Exchange',
  Strings.euroWallet: 'EURO eWallet',
  Strings.realTimeChart: '@NT eWallet',
  Strings.antWallet: 'Real-time chart',
  Strings.upgradeToStandard: 'Upgrade to Standard',
  Strings.contactAndSupport: 'Contact & support',
  Strings.faq: 'FAQ',
  Strings.privacyPolicyAndCookies: 'Privacy policy & cookies',
  Strings.softwareLicense: 'Software license',
  Strings.terms: 'Terms',
  Strings.blockedAccount: 'Blocked account',
  Strings.editPersonalData: 'Edit personal data',
};
