import 'package:app_in_mail/constants/strings/string_keys.dart';
///english translations, each new String must be also added to the other
///translation files and the key must be a constant
final localizedStringsEn = {
  Strings.inbox: 'Inbox',
  Strings.enter: 'NEXT',
  Strings.errorWhileGettingEmailsList: 'Error while getting emails list.',
  Strings.errorWhileTryingToSignIn: 'Error while trying to sign in',
  Strings.email: 'E-mail',
  Strings.password: 'Password',
  Strings.signIn: 'Sign in with login',
  Strings.logout: 'Logout',
  Strings.invalidCredentials: "Invalid user name or password.",
  Strings.noInternet: 'You are not connected to internet.',
  Strings.welcomeTitle1: "Email became",
  Strings.welcomeTitle2: "active!",
  Strings.welcomeMsg: "If earlier the emails contained only text and graphics, now the emails have actions! Email content became active - interact with it like with App!",
  Strings.welcomeBtnOK: "OKAY,I SEE",
  Strings.registerMsg: 'Do not have an account?',
  Strings.registerBtn: "Sign Up",
  Strings.forgotPasswordBtn: "Forgot password?",
  Strings.moveTo: 'Move to',
  Strings.markAsUnread: 'Mark as unread',
  Strings.delete: 'Delete',
  Strings.exchange: 'Exchange',
  Strings.euroWallet: 'EURO eWallet',
  Strings.realTimeChart: 'Real-time chart',
  Strings.antWallet: '@NT eWallet',
  Strings.upgradeToStandard: 'Upgrade to Standard',
  Strings.contactAndSupport: 'Contact & support',
  Strings.faq: 'FAQ',
  Strings.privacyPolicyAndCookies: 'Privacy policy & cookies',
  Strings.softwareLicense: 'Software license',
  Strings.terms: 'Terms',
  Strings.blockedAccount: 'Blocked account',
  Strings.editPersonalData: 'Edit personal data',
  Strings.personalData: 'Personal data',
  Strings.login: 'Login',
  Strings.firstName: 'First name',
  Strings.lastName: 'Last name',
  Strings.language: 'Language',
  Strings.save: 'SAVE',
  Strings.thisFieldisRequired: 'This field is required',
  Strings.youHave: 'YOU\nHAVE', 
  Strings.youGet: 'YOU\nGET', 
  Strings.exchangeEuroWith: 'Exchange euro with:', 
  Strings.upgradeAccount: 'Upgrade account',
  Strings.lightAccount: 'Light account',
  Strings.lightAccountIn: 'IN',
  Strings.lightAccountOut: 'OUT',
  Strings.lightAccountMax: 'MAX',
  Strings.currentBalance: 'Current balance',
  Strings.buyAnt: 'Buy @NT',
  Strings.exchangeAntToEur: 'Exchange @NT to EUR',
  Strings.transfer: 'Transfer',
  Strings.activity: 'Activity',
  Strings.depositEur: 'Deposit EUR',
  Strings.exchangeEurToAnd: 'Exchange EUR to @NT',
  Strings.withdraw: 'Withdraw',
};
