import 'package:app_in_mail/constants/strings/string_keys.dart';

final localizedStringsFr = {
  Strings.inbox: 'Inbox_FR',
  Strings.enter: 'NEXT_FR',
  Strings.errorWhileGettingEmailsList: 'Error while getting emails list._FR',
  Strings.errorWhileTryingToSignIn: 'Error while trying to sign in_FR',
  Strings.email: 'E-mail_FR',
  Strings.password: 'Password_FR',
  Strings.signIn: 'Sign in with login_FR',
  Strings.logout: 'Logout_FR',
  Strings.invalidCredentials: 'Invalid user name or password._FR.',
  Strings.noInternet: 'You are not connected to internet._FR',
  Strings.welcomeTitle1: 'Email became_FR',
  Strings.welcomeTitle2: 'active!_FR',
  Strings.welcomeMsg: 'If earlier the emails contained only text and graphics, now the emails have actions! Email content became active - interact with it like with App!_FR',
  Strings.welcomeBtnOK: 'OKAY,I SEE_FR',
  Strings.registerMsg: 'Do not have an account?_FR',
  Strings.registerBtn: 'Sign Up_FR',
  Strings.forgotPasswordBtn: 'Forgot password?_FR',
  Strings.moveTo: 'Move to_FR',
  Strings.markAsUnread: 'Mark as unread_FR',
  Strings.delete: 'Delete_FR',
  Strings.exchange: 'Exchange_FR',
  Strings.euroWallet: 'EURO eWallet_FR',
  Strings.realTimeChart: 'Real-time chart_FR',
  Strings.antWallet: '@NT eWallet_FR',
  Strings.upgradeToStandard: 'Upgrade to Standard_FR',
  Strings.contactAndSupport: 'Contact & support_FR',
  Strings.faq: 'FAQ_FR',
  Strings.privacyPolicyAndCookies: 'Privacy policy & cookies_FR',
  Strings.softwareLicense: 'Software license_FR',
  Strings.terms: 'Terms_FR',
  Strings.blockedAccount: 'Blocked account_FR',
  Strings.editPersonalData: 'Edit personal data_FR',
  Strings.personalData: 'Personal data_FR',
  Strings.login: 'Login_FR',
  Strings.firstName: 'First name_FR',
  Strings.lastName: 'Last name_FR',
  Strings.language: 'Language_FR',
  Strings.save: 'SAVE_FR',
  Strings.thisFieldisRequired: 'This field is required_FR',
  Strings.youHave: 'YOU\nHAVE_FR', 
  Strings.youGet: 'YOU\nGET_FR', 
  Strings.exchangeEuroWith: 'Exchange euro with:_FR', 
  Strings.upgradeAccount: 'Upgrade account_FR',
  Strings.lightAccount: 'Light account_FR',
  Strings.lightAccountIn: 'IN_FR',
  Strings.lightAccountOut: 'OUT_FR',
  Strings.lightAccountMax: 'MAX_FR',
  Strings.currentBalance: 'Current balance_FR',
  Strings.buyAnt: 'Buy @NT_FR',
  Strings.exchangeAntToEur: 'Exchange @NT to EUR_FR',
  Strings.transfer: 'Transfer_FR',
  Strings.activity: 'Activity_FR',
  Strings.depositEur: 'Deposit EUR_FR',
  Strings.exchangeEurToAnt: 'Exchange EUR to @NT_FR',
  Strings.withdraw: 'Withdraw_FR',
  Strings.add: 'Add_FR',
  Strings.compose: 'Compose_FR',
  Strings.to: 'To_FR',
  Strings.subject: 'Subject_FR',
  Strings.message: 'Message_FR',
  Strings.twelveHours: '12 h_FR',
  Strings.twentyFourHours: '24 h_FR',
  Strings.sevenDays: '7 Days_FR',
  Strings.twoWeeks: '2 weeks_FR',
  Strings.oneMonth: '1M_FR',
  Strings.sixMonths: '6M_FR',
  Strings.oneYear: 'Year_FR',
  Strings.antMktCapp: '@NT Mkt. Cap._FR',
  Strings.agtSupply: 'AGT Supply_FR',
  Strings.antSupply: '@NT Supply_FR',
};
